# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Cloudflare

on:
  push:
    branches:
      - main
  schedule:
    # Schedule to run at 00:00 and 12:00 every day
    - cron: '0 0,12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Use taobao registry
        run: npm config set registry https://registry.npmmirror.com/
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: generate ig
        run: pnpm run ig
        env:
          IG_TOKEN: ${{secrets.IG_TOKEN}}
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
